query availableSecrets($botIds: [ID!]!, $contactIds: [ID!]!) {
  relatedSecrets(
    last: 100
    botIds: $botIds
    kind: [personal]
    visibility: [protected]
    includeOwn: { kind: [personal], visibility: [public, private, protected] }
  ) {
    edges {
      node {
        id
        name
        description

        contacts(contactIds: $contactIds) {
          verification {
            status
            action {
              type
              url
            }
          }
        }
      }
    }
  }
}
