import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  INSTAGRAM_CONVERSATION_API_PATH,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/instagram'

const INSTAGRAM_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/instagram' satisfies typeof INSTAGRAM_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Instagram integration abilities.
 */
const abilities = {
  'instagram/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'google',
      icon: '@logo/instagram.com',
      name: 'Start Instagram Conversation',
      description:
        'Initiates a new conversation by sending a message to an Instagram recipient.',
      tags: ['instagram', 'conversation', 'message', 'integration'],
      path: INSTAGRAM_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        instagramIntegrationId: field({
          name: 'instagramIntegrationId',
          description: 'The ID of the Instagram integration to use',
          placeholder: true,
        }),
        instagramUserId: field({
          name: 'instagramUserId',
          description:
            'The Instagram professional account ID sending the message',
          placeholder: true,
        }),
        recipientId: field({
          name: 'recipientId',
          description: 'The Instagram recipient ID from a prior interaction',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
