import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  SLACK_CONVERSATION_API_PATH,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/slack'

// --- Path Constants ---

const SLACK_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/slack' satisfies typeof SLACK_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Slack integration abilities.
 */
const abilities = {
  'slack/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'slack',
      icon: '@logo/slack.com',
      name: 'Start Slack Conversation',
      description:
        'Initiates a new conversation by sending a message to a Slack channel or direct message.',
      tags: ['slack', 'conversation', 'message', 'integration'],
      path: SLACK_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        slackIntegrationId: field({
          name: 'slackIntegrationId',
          description: 'The ID of the Slack integration to use',
          placeholder: true,
        }),
        channel: field({
          name: 'channel',
          description:
            'The Slack channel or user to send to. Supports: channel IDs (C01234567), DM IDs (D01234567), #channel-name, or @username',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
