import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
  WHATSAPP_CONVERSATION_API_PATH,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/whatsapp'

// --- Path Constants ---

const WHATSAPP_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/whatsapp' satisfies typeof WHATSAPP_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit WhatsApp integration abilities.
 */
const abilities = {
  'whatsapp/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'whatsapp',
      icon: '@logo/whatsapp.com',
      name: 'Start WhatsApp Conversation',
      description:
        'Initiates a new conversation by sending a message to a WhatsApp user.',
      tags: ['whatsapp', 'conversation', 'message', 'integration'],
      path: WHATSAPP_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        whatsappIntegrationId: field({
          name: 'whatsappIntegrationId',
          description: 'The ID of the WhatsApp integration to use',
          placeholder: true,
        }),
        to: field({
          name: 'to',
          description:
            'The recipient phone number in international format (e.g. 14155238886)',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The initial message text to send to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
