import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  END_CALL_HANDLER_NAME,
  EndCallSchema,
  ROUTE_CALL_HANDLER_NAME,
  RouteCallSchema,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
  TWILIO_CONVERSATION_API_PATH,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/twilio'

// --- Path Constants ---

const TWILIO_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/twilio' satisfies typeof TWILIO_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Twilio integration abilities.
 */
const abilities = {
  'twilio/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'twilio',
      icon: '@logo/twilio.com',
      name: 'Start Twilio Conversation',
      description:
        'Initiates a new conversation by sending an SMS message or starting a phone call through Twilio.',
      tags: ['twilio', 'conversation', 'sms', 'call', 'integration'],
      path: TWILIO_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        twilioIntegrationId: field({
          name: 'twilioIntegrationId',
          description: 'The ID of the Twilio integration to use',
          placeholder: true,
        }),
        channel: field({
          name: 'channel',
          description: 'The Twilio channel to use',
          enum: ['sms', 'call'],
          default: 'sms',
          optional: true,
        }),
        from: field({
          name: 'from',
          description: 'The Twilio sender phone number in international format',
          placeholder: true,
        }),
        to: field({
          name: 'to',
          description: 'The recipient phone number in international format',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
  'twilio/call/route[by-id]': createAuxiliaryTemplate<RouteCallSchema>({
    provider: 'twilio',
    icon: '@logo/twilio.com',
    name: 'Route Twilio Call',
    description:
      'Routes an active Twilio call to another phone number by redirecting the live Call SID to TwiML.',
    tags: ['twilio', 'voice', 'call', 'route', 'transfer', 'integration'],
    path: TWILIO_API_PATH,
    handler: 'routeCall' satisfies typeof ROUTE_CALL_HANDLER_NAME,
    instruction: {
      twilioIntegrationId: field({
        name: 'twilioIntegrationId',
        description: 'The ID of the Twilio integration to use',
        placeholder: true,
      }),
      callSid: field({
        name: 'callSid',
        description:
          'The Twilio Call SID of the active call leg to route. Use the caller leg SID.',
        placeholder: true,
      }),
      to: field({
        name: 'to',
        description:
          'The destination phone number to route the active call to in international format',
        placeholder: true,
      }),
    },
    options: {
      auth: 'internal',
      context: ['conversation'],
    },
  }),
  'twilio/call/end[by-id]': createAuxiliaryTemplate<EndCallSchema>({
    provider: 'twilio',
    icon: '@logo/twilio.com',
    name: 'End Twilio Call',
    description: 'Ends an active Twilio call by completing the live Call SID.',
    tags: ['twilio', 'voice', 'call', 'end', 'hangup', 'integration'],
    path: TWILIO_API_PATH,
    handler: 'endCall' satisfies typeof END_CALL_HANDLER_NAME,
    instruction: {
      twilioIntegrationId: field({
        name: 'twilioIntegrationId',
        description: 'The ID of the Twilio integration to use',
        placeholder: true,
      }),
      callSid: field({
        name: 'callSid',
        description:
          'The Twilio Call SID of the active call leg to end. Use the caller leg SID.',
        placeholder: true,
      }),
    },
    options: {
      auth: 'internal',
      context: ['conversation'],
    },
  }),
}

export default abilities
