import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  GOOGLECHAT_CONVERSATION_API_PATH,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/googlechat'

const GOOGLECHAT_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/googlechat' satisfies typeof GOOGLECHAT_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Google Chat integration abilities.
 */
const abilities = {
  'googlechat/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'google',
      icon: '@logo/google.com',
      name: 'Start Google Chat Conversation',
      description:
        'Initiates a new conversation by sending a message to a Google Chat space or direct message.',
      tags: ['googlechat', 'google', 'conversation', 'message', 'integration'],
      path: GOOGLECHAT_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        googlechatIntegrationId: field({
          name: 'googlechatIntegrationId',
          description: 'The ID of the Google Chat integration to use',
          placeholder: true,
        }),
        space: field({
          name: 'space',
          description:
            'The Google Chat space resource name or user identifier to send to',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
