import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
  TELEGRAM_CONVERSATION_API_PATH,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/telegram'

// --- Path Constants ---

const TELEGRAM_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/telegram' satisfies typeof TELEGRAM_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Telegram integration abilities.
 */
const abilities = {
  'telegram/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'telegram',
      icon: '@logo/telegram.org',
      name: 'Start Telegram Conversation',
      description:
        'Initiates a new conversation by sending a message to a Telegram chat.',
      tags: ['telegram', 'conversation', 'message', 'integration'],
      path: TELEGRAM_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        telegramIntegrationId: field({
          name: 'telegramIntegrationId',
          description: 'The ID of the Telegram integration to use',
          placeholder: true,
        }),
        chatId: field({
          name: 'chatId',
          description:
            'The Telegram chat ID to send the message to. This can be a user ID, group chat ID, or channel ID',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
