import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  MICROSOFTTEAMS_CONVERSATION_API_PATH,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/microsoftteams'

const MICROSOFTTEAMS_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/microsoftteams' satisfies typeof MICROSOFTTEAMS_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Microsoft Teams integration abilities.
 */
const abilities = {
  'microsoftteams/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'microsoft',
      icon: '@logo/microsoft.com',
      name: 'Start Teams Conversation',
      description:
        'Initiates a new conversation by sending a message to a Microsoft Teams conversation.',
      tags: [
        'microsoftteams',
        'teams',
        'conversation',
        'message',
        'integration',
      ],
      path: MICROSOFTTEAMS_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        microsoftteamsIntegrationId: field({
          name: 'microsoftteamsIntegrationId',
          description: 'The ID of the Microsoft Teams integration to use',
          placeholder: true,
        }),
        conversationId: field({
          name: 'conversationId',
          description:
            'The Bot Framework conversation ID to send the message to',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
