import {
  createConversationFetchTemplate,
  createConversationListTemplate,
  createConversationSearchTemplate,
  field,
} from '@/lib/ability.template'

/**
 * Catalogue of ChatBotKit conversation abilities.
 */
const abilities = {
  // @note CRUD operations do not make sense for conversations as they are
  // generated by the system based on interactions

  // @note the context of these is all conversations within the ChatBotKit
  // account

  'conversation/search': createConversationSearchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Search Conversations',
    description: 'Search conversations by query',
    tags: ['conversation', 'search', 'alpha'],
    commentary:
      '**NOTE:** This ability searches all conversations in the account. It should only be used by system agents that are not directly exposed to users.',
    instruction: {
      '@scope': 'user',
      query: field({
        name: 'query',
        description: 'the search query to find conversations',
      }),
    },
  }),

  'conversation/list': createConversationListTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'List Conversations',
    description: 'List all conversations',
    tags: ['conversation', 'list', 'beta'],
    commentary:
      '**NOTE:** This ability lists all conversations in the account. It should only be used by system agents that are not directly exposed to users.',
    instruction: {
      '@scope': 'user',
    },
  }),

  'conversation/fetch[by-id]': createConversationFetchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Fetch Conversation',
    description: 'Fetch details of a specific conversation',
    tags: ['conversation', 'fetch', 'beta'],
    commentary:
      '**NOTE:** This ability fetches a conversation in the account by ID. It should only be used by system agents that are not directly exposed to users.',
    instruction: {
      '@scope': 'user',
      conversationId: field({
        name: 'conversationId',
        description: 'the ID of the conversation to fetch',
      }),
    },
  }),

  // @note the context of these is all conversations associated with a specific
  // contact

  'conversation/search[contact]': createConversationSearchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Search Conversations',
    description: 'Search conversations by query',
    tags: ['conversation', 'search', 'contact', 'alpha'],
    commentary:
      '**NOTE:** This ability searches conversations for the contact in the conversational context.',
    instruction: {
      '@scope': 'contact',
      query: field({
        name: 'query',
        description: 'the search query to find conversations',
      }),
    },
  }),

  'conversation/list[contact]': createConversationListTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'List Conversations',
    description: 'List all conversations',
    tags: ['conversation', 'list', 'contact', 'beta'],
    commentary:
      '**NOTE:** This ability list conversations for the contact in the conversational context.',
    instruction: {
      '@scope': 'contact',
    },
  }),

  'conversation/fetch[contact][by-id]': createConversationFetchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Fetch Conversation',
    description: 'Fetch details of a specific conversation',
    tags: ['conversation', 'fetch', 'contact', 'beta'],
    commentary:
      '**NOTE:** This ability fetches a conversation for the contact in the conversational context.',
    instruction: {
      '@scope': 'contact',
      conversationId: field({
        name: 'conversationId',
        description: 'the ID of the conversation to fetch',
      }),
    },
  }),

  // @note the context of these is all conversations associated with a specific
  // bot

  'conversation/search[bot]': createConversationSearchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Search Conversations',
    description: 'Search conversations by query',
    tags: ['conversation', 'search', 'bot', 'alpha'],
    commentary:
      '**NOTE:** This ability searches conversations for the bot itself.',
    instruction: {
      '@scope': 'bot',
      query: field({
        name: 'query',
        description: 'the search query to find conversations',
      }),
    },
  }),

  'conversation/list[bot]': createConversationListTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'List Conversations',
    description: 'List all conversations',
    tags: ['conversation', 'list', 'bot', 'beta'],
    commentary: '**NOTE:** This ability list conversations for the bot itself.',
    instruction: {
      '@scope': 'bot',
    },
  }),

  'conversation/fetch[bot][by-id]': createConversationFetchTemplate({
    provider: 'cbk',
    icon: '@logo/chatbotkit.com',
    name: 'Fetch Conversation',
    description: 'Fetch details of a specific conversation',
    tags: ['conversation', 'fetch', 'bot', 'beta'],
    commentary:
      '**NOTE:** This ability fetches a conversation for the bot itself.',
    instruction: {
      '@scope': 'bot',
      conversationId: field({
        name: 'conversationId',
        description: 'the ID of the conversation to fetch',
      }),
    },
  }),
}

export default abilities
