import { createAuxiliaryTemplate, field } from '@/lib/ability.template'

import type {
  DISCORD_CONVERSATION_API_PATH,
  START_CONVERSATION_HANDLER_NAME,
  StartConversationSchema,
} from '@/pages/api/auxiliary/skillset/ability/chatbotkit/integration/discord'

// --- Path Constants ---

const DISCORD_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/discord' satisfies typeof DISCORD_CONVERSATION_API_PATH

/**
 * Catalogue of ChatBotKit Discord integration abilities.
 */
const abilities = {
  'discord/conversation/start[by-id]':
    createAuxiliaryTemplate<StartConversationSchema>({
      provider: 'discord',
      icon: '@logo/discord.com',
      name: 'Start Discord Conversation',
      description:
        'Initiates a new conversation by sending a message to a Discord channel.',
      tags: ['discord', 'conversation', 'message', 'integration'],
      path: DISCORD_API_PATH,
      handler:
        'startConversation' satisfies typeof START_CONVERSATION_HANDLER_NAME,
      instruction: {
        discordIntegrationId: field({
          name: 'discordIntegrationId',
          description: 'The ID of the Discord integration to use',
          placeholder: true,
        }),
        channelId: field({
          name: 'channelId',
          description: 'The Discord channel ID to send the message to',
          placeholder: true,
        }),
        text: field({
          name: 'text',
          description:
            'The opening instruction telling the agent what to say or do to start the conversation',
          placeholder: true,
        }),
        context: field({
          name: 'context',
          description:
            'Optional context about the recipient or conversation, typically generated by the agent',
          placeholder: true,
          optional: true,
        }),
      },
      options: {
        auth: 'internal',
        context: ['conversation'],
      },
    }),
}

export default abilities
