import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/discord/[discordIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const DISCORD_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/discord'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

// --- Schemas ---

const startConversationSchema = z.object({
  discordIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Discord integration to use'),
  channelId: z
    .string()
    .min(1)
    .describe('The Discord channel ID to send the message to'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the channel'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.discord.startConversation'
  )

  const { discordIntegrationId, channelId, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  // Fetch the Discord integration and verify user ownership

  const discordIntegration =
    await prisma.discordIntegration.findUniqueByIdentifier(
      session.user,
      discordIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          botToken: true,
        },
      }
    )

  if (!discordIntegration) {
    throw new UserInputError('Discord integration not found')
  }

  if (discordIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Discord integration')
  }

  if (!discordIntegration.botToken) {
    throw new UserInputError('Discord integration does not have a bot token')
  }

  // Start conversation using the integration queue system
  // @note this will send the initial message and create a conversation

  await sendEvent(discordIntegration.id, {
    type: 'initiate',
    payload: {
      channelId,

      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    channelId,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
