import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import type { Session } from '@/lib/session.handler'

import {
  SEND_EVENT_TYPE,
  sendEvent,
} from '@/pages/api/v1/integration/email/[emailIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const EMAIL_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/email'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

// --- Schemas ---

const startConversationSchema = z.object({
  emailIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the email integration to use'),
  email: z.string().email().describe('The recipient email address to send to'),
  subject: z.string().min(1).describe('The subject line of the email'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the recipient'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  _headers: Headers
) {
  debug('email/conversation/start', { parameters })

  const { emailIntegrationId, email, subject, text, context } = parameters

  // Fetch the email integration and verify user ownership

  const emailIntegration = await prisma.emailIntegration.findUniqueByIdentifier(
    session.user,
    emailIntegrationId,
    {
      select: {
        id: true,
        userId: true,
      },
    }
  )

  if (!emailIntegration) {
    throw new UserInputError('Email integration not found')
  }

  if (emailIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this email integration')
  }

  // Start conversation using the email integration queue
  // @note this will send the initial email and create a conversation

  await sendEvent(emailIntegration.id, {
    type: SEND_EVENT_TYPE,
    payload: {
      email,
      subject,
      text,
      ...(context ? { context } : {}),
    },
  })

  return {
    success: true,
    email,
    subject,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
