import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/googlechat/[googlechatIntegrationId]/queue'

import { z } from 'zod'

export const GOOGLECHAT_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/googlechat'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

const startConversationSchema = z.object({
  googlechatIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Google Chat integration to use'),
  space: z
    .string()
    .min(1)
    .describe(
      'The Google Chat space resource name or user identifier to send to'
    ),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the space or user'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.googlechat.startConversation'
  )

  const { googlechatIntegrationId, space, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  const googlechatIntegration =
    await prisma.googlechatIntegration.findUniqueByIdentifier(
      session.user,
      googlechatIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          serviceAccountKey: true,
        },
      }
    )

  if (!googlechatIntegration) {
    throw new UserInputError('Google Chat integration not found')
  }

  if (googlechatIntegration.userId !== session.user.id) {
    throw new UserInputError(
      'Not authorized to use this Google Chat integration'
    )
  }

  if (!googlechatIntegration.serviceAccountKey) {
    throw new UserInputError(
      'Google Chat integration does not have a service account key'
    )
  }

  await sendEvent(googlechatIntegration.id, {
    type: 'initiate',
    payload: {
      space,
      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    space,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
