import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/instagram/[instagramIntegrationId]/queue'

import { z } from 'zod'

export const INSTAGRAM_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/instagram'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

const startConversationSchema = z.object({
  instagramIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Instagram integration to use'),
  instagramUserId: z
    .string()
    .min(1)
    .describe('The Instagram professional account ID sending the message'),
  recipientId: z
    .string()
    .min(1)
    .describe('The Instagram recipient ID from a prior interaction'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the recipient'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.instagram.startConversation'
  )

  const {
    instagramIntegrationId,
    instagramUserId,
    recipientId,
    text,
    context,
  } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  const instagramIntegration =
    await prisma.instagramIntegration.findUniqueByIdentifier(
      session.user,
      instagramIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          accessToken: true,
        },
      }
    )

  if (!instagramIntegration) {
    throw new UserInputError('Instagram integration not found')
  }

  if (instagramIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Instagram integration')
  }

  if (!instagramIntegration.accessToken) {
    throw new UserInputError(
      'Instagram integration does not have an access token'
    )
  }

  await sendEvent(instagramIntegration.id, {
    type: 'initiate',
    payload: {
      instagramUserId,
      recipientId,
      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    instagramUserId,
    recipientId,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
