import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/messenger/[messengerIntegrationId]/queue'

import { z } from 'zod'

export const MESSENGER_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/messenger'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

const startConversationSchema = z.object({
  messengerIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Messenger integration to use'),
  pageId: z
    .string()
    .min(1)
    .describe('The Facebook Page ID sending the message'),
  recipientId: z
    .string()
    .min(1)
    .describe('The Messenger recipient PSID from a prior interaction'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the recipient'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.messenger.startConversation'
  )

  const { messengerIntegrationId, pageId, recipientId, text, context } =
    parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  const messengerIntegration =
    await prisma.messengerIntegration.findUniqueByIdentifier(
      session.user,
      messengerIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          accessToken: true,
        },
      }
    )

  if (!messengerIntegration) {
    throw new UserInputError('Messenger integration not found')
  }

  if (messengerIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Messenger integration')
  }

  if (!messengerIntegration.accessToken) {
    throw new UserInputError(
      'Messenger integration does not have an access token'
    )
  }

  await sendEvent(messengerIntegration.id, {
    type: 'initiate',
    payload: {
      pageId,
      recipientId,
      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    pageId,
    recipientId,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
