import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/microsoftteams/[microsoftteamsIntegrationId]/queue'

import { z } from 'zod'

export const MICROSOFTTEAMS_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/microsoftteams'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

const startConversationSchema = z.object({
  microsoftteamsIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Microsoft Teams integration to use'),
  conversationId: z
    .string()
    .min(1)
    .describe('The Bot Framework conversation ID to send the message to'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the conversation'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.microsoftteams.startConversation'
  )

  const { microsoftteamsIntegrationId, conversationId, text, context } =
    parameters

  const linkedConversationId = getHeader(
    headers,
    'x-chatbotkit-conversation-id'
  )

  const microsoftteamsIntegration =
    await prisma.microsoftteamsIntegration.findUniqueByIdentifier(
      session.user,
      microsoftteamsIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          botFrameworkAppId: true,
          botFrameworkAppSecret: true,
        },
      }
    )

  if (!microsoftteamsIntegration) {
    throw new UserInputError('Microsoft Teams integration not found')
  }

  if (microsoftteamsIntegration.userId !== session.user.id) {
    throw new UserInputError(
      'Not authorized to use this Microsoft Teams integration'
    )
  }

  if (!microsoftteamsIntegration.botFrameworkAppId) {
    throw new UserInputError(
      'Microsoft Teams integration does not have a Bot Framework app ID'
    )
  }

  if (!microsoftteamsIntegration.botFrameworkAppSecret) {
    throw new UserInputError(
      'Microsoft Teams integration does not have a Bot Framework app secret'
    )
  }

  await sendEvent(microsoftteamsIntegration.id, {
    type: 'initiate',
    payload: {
      conversationId,
      text,

      ...(context
        ? {
            context: {
              linkedConversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    conversationId,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
