import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/slack/[slackIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const SLACK_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/slack'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

// --- Schemas ---

const startConversationSchema = z.object({
  slackIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Slack integration to use'),
  channel: z.string().min(1).describe('The Slack channel ID to send to'),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the user'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.slack.startConversation'
  )

  const { slackIntegrationId, channel, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  // Fetch the Slack integration and verify user ownership

  const slackIntegration = await prisma.slackIntegration.findUniqueByIdentifier(
    session.user,
    slackIntegrationId,
    {
      select: {
        id: true,
        userId: true,
        botToken: true,
      },
    }
  )

  if (!slackIntegration) {
    throw new UserInputError('Slack integration not found')
  }

  if (slackIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Slack integration')
  }

  if (!slackIntegration.botToken) {
    throw new UserInputError('Slack integration does not have a bot token')
  }

  // Start conversation using the integration queue system
  // @note this will send the initial message and create a conversation

  await sendEvent(slackIntegration.id, {
    type: 'initiate',
    payload: {
      channelId: channel,

      text: text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    channel,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
