import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/telegram/[telegramIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const TELEGRAM_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/telegram'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

// --- Schemas ---

const startConversationSchema = z.object({
  telegramIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Telegram integration to use'),
  chatId: z
    .string()
    .min(1)
    .describe(
      'The Telegram chat ID to send the message to. This can be a user ID, group chat ID, or channel ID'
    ),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the chat'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.telegram.startConversation'
  )

  const { telegramIntegrationId, chatId, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  // Fetch the Telegram integration and verify user ownership

  const telegramIntegration =
    await prisma.telegramIntegration.findUniqueByIdentifier(
      session.user,
      telegramIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          botToken: true,
        },
      }
    )

  if (!telegramIntegration) {
    throw new UserInputError('Telegram integration not found')
  }

  if (telegramIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Telegram integration')
  }

  if (!telegramIntegration.botToken) {
    throw new UserInputError('Telegram integration does not have a bot token')
  }

  // Start conversation using the integration queue system
  // @note this will send the initial message and create a conversation

  await sendEvent(telegramIntegration.id, {
    type: 'initiate',
    payload: {
      chatId,

      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    chatId,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
