import respond from '@chatbotkit-dev/respond'

import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'
import {
  listTwilioIncomingPhoneNumbers,
  updateTwilioCall,
} from '@/lib/twilio.api'
import {
  normalizeTwilioMessageAddress,
  normalizeTwilioPhoneNumber,
} from '@/lib/twilio.phone'
import { createTwilioDialXml } from '@/lib/twilio.twiml'

import {
  INITIATE_EVENT_TYPE,
  sendEvent,
} from '@/pages/api/v1/integration/twilio/[twilioIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const TWILIO_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/twilio'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'
export const ROUTE_CALL_HANDLER_NAME = 'routeCall'
export const END_CALL_HANDLER_NAME = 'endCall'

// --- Schemas ---

const startConversationSchema = z.object({
  twilioIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Twilio integration to use'),
  channel: z
    .enum(['sms', 'call'])
    .default('sms')
    .describe('The Twilio channel to use'),
  from: z
    .string()
    .min(1)
    .describe('The Twilio sender phone number in international format'),
  to: z
    .string()
    .min(1)
    .describe('The recipient phone number in international format'),
  text: z
    .string()
    .min(1)
    .describe('The initial instruction to use to start the conversation'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

const routeCallSchema = z.object({
  twilioIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Twilio integration to use'),
  callSid: z
    .string()
    .min(1)
    .describe('The Twilio Call SID of the active call leg to route'),
  to: z
    .string()
    .min(1)
    .describe('The phone number to route the active call to'),
})

export type RouteCallSchema = z.infer<typeof routeCallSchema>

const endCallSchema = z.object({
  twilioIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the Twilio integration to use'),
  callSid: z
    .string()
    .min(1)
    .describe('The Twilio Call SID of the active call leg to end'),
})

export type EndCallSchema = z.infer<typeof endCallSchema>

// --- Helpers ---

function normalizeTwilioStartAddress({
  channel,
  field,
  value,
}: {
  channel: StartConversationSchema['channel']
  field: 'from' | 'to'
  value: string
}) {
  const normalized =
    channel === 'sms'
      ? normalizeTwilioMessageAddress(value, {
          allowAlphanumericSender: field === 'from',
        })
      : normalizeTwilioPhoneNumber(value)

  if (!normalized) {
    throw new UserInputError(
      `Invalid Twilio ${field} phone number for ${channel}`
    )
  }

  return normalized
}

/**
 * Resolves the sender against the integration's actual Twilio phone numbers.
 *
 * @note The `from` value is model-supplied and can be hallucinated. If it does
 * not match an available number we fall back to the only number we have (when
 * there is exactly one) or surface the list so the caller can pick a valid one.
 *
 * @throws {UserInputError} When no numbers are available, or when `from` does
 * not match any of several available numbers.
 */
export function resolveTwilioFromNumber({
  from,
  availableNumbers,
}: {
  from: string
  availableNumbers: string[]
}) {
  const normalizedAvailable = availableNumbers
    .map((value) => normalizeTwilioPhoneNumber(value))
    .filter((value): value is string => Boolean(value))

  if (normalizedAvailable.length === 0) {
    throw new UserInputError(
      'No Twilio phone numbers are available on this integration'
    )
  }

  if (normalizedAvailable.includes(from)) {
    return from
  }

  if (normalizedAvailable.length === 1) {
    return normalizedAvailable[0]
  }

  throw new UserInputError(
    `The "from" number ${from} is not one of the available Twilio phone numbers: ${normalizedAvailable.join(', ')}`
  )
}

/**
 * Hands Twilio a URL that answers with the markup we already have.
 *
 * @note a failure to issue one is left to propagate rather than re-raised as a
 * `UserInputError`, which is what this did before. The old classification was
 * wrong in a way that mattered: an unconfigured backend is a deployment fault,
 * and calling it user input is exactly what kept it out of the error reporter -
 * so a missing variable would have shown up as calls quietly failing to
 * connect, with nothing captured. Unhandled here, it is captured and still
 * reaches the model through the handler's error stream.
 */
function createTwilioRespondUrl(xml: string) {
  return respond.urlFor({
    body: xml,
    contentType: 'text/xml; charset=utf-8',
  })
}

function createTwilioRouteCallUrl(to: string) {
  return createTwilioRespondUrl(createTwilioDialXml(to))
}

async function getTwilioIntegration(
  session: Session,
  twilioIntegrationId: string
) {
  const twilioIntegration =
    await prisma.twilioIntegration.findUniqueByIdentifier(
      session.user,
      twilioIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          accountSid: true,
          authToken: true,
        },
      }
    )

  if (!twilioIntegration) {
    throw new UserInputError('Twilio integration not found')
  }

  if (twilioIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Twilio integration')
  }

  if (!twilioIntegration.accountSid) {
    throw new UserInputError('Twilio integration does not have an Account SID')
  }

  if (!twilioIntegration.authToken) {
    throw new UserInputError('Twilio integration does not have an auth token')
  }

  return twilioIntegration
}

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('twilio/conversation/start', { parameters })

  const { twilioIntegrationId, channel, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  const requestedFrom = normalizeTwilioStartAddress({
    channel,
    field: 'from',
    value: parameters.from,
  })

  const to = normalizeTwilioStartAddress({
    channel,
    field: 'to',
    value: parameters.to,
  })

  const twilioIntegration = await getTwilioIntegration(
    session,
    twilioIntegrationId
  )

  const availableNumbers = await listTwilioIncomingPhoneNumbers({
    accountSid: twilioIntegration.accountSid,
    authToken: twilioIntegration.authToken,
  })

  const from = resolveTwilioFromNumber({
    from: requestedFrom,
    availableNumbers,
  })

  await sendEvent(twilioIntegration.id, {
    type: INITIATE_EVENT_TYPE,
    payload: {
      channel,
      from,
      to,
      text,
      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    channel,
    from,
    to,
  }
}

async function routeCall(
  session: Session,
  parameters: z.infer<typeof routeCallSchema>
) {
  debug('twilio/call/route', { parameters })

  const { twilioIntegrationId, callSid } = parameters

  const to = normalizeTwilioPhoneNumber(parameters.to)

  if (!to) {
    throw new UserInputError('Invalid Twilio route phone number')
  }

  const twilioIntegration =
    await prisma.twilioIntegration.findUniqueByIdentifier(
      session.user,
      twilioIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          accountSid: true,
          authToken: true,
        },
      }
    )

  if (!twilioIntegration) {
    throw new UserInputError('Twilio integration not found')
  }

  if (twilioIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this Twilio integration')
  }

  if (!twilioIntegration.accountSid) {
    throw new UserInputError('Twilio integration does not have an Account SID')
  }

  if (!twilioIntegration.authToken) {
    throw new UserInputError('Twilio integration does not have an auth token')
  }

  const url = createTwilioRouteCallUrl(to)

  await updateTwilioCall({
    accountSid: twilioIntegration.accountSid,
    authToken: twilioIntegration.authToken,
    callSid,
    url,
    method: 'POST',
  })

  return {
    success: true,
    callSid,
    to,
  }
}

async function endCall(
  session: Session,
  parameters: z.infer<typeof endCallSchema>
) {
  debug('twilio/call/end', { parameters })

  const { twilioIntegrationId, callSid } = parameters

  const twilioIntegration = await getTwilioIntegration(
    session,
    twilioIntegrationId
  )

  await updateTwilioCall({
    accountSid: twilioIntegration.accountSid,
    authToken: twilioIntegration.authToken,
    callSid,
    status: 'completed',
  })

  return {
    success: true,
    callSid,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
  [ROUTE_CALL_HANDLER_NAME]: {
    schema: routeCallSchema,
    fn: routeCall,
  },
  [END_CALL_HANDLER_NAME]: {
    schema: endCallSchema,
    fn: endCall,
  },
})
