import prisma from '@/prisma/client'

import { authenticatedMultiHandler } from '@/lib/auxiliary.handler'
import debug from '@/lib/debug'
import { UserInputError } from '@/lib/error'
import { getHeader } from '@/lib/header'
import type { Session } from '@/lib/session.handler'

import { sendEvent } from '@/pages/api/v1/integration/whatsapp/[whatsappIntegrationId]/queue'

import { z } from 'zod'

// --- Path and Handler Constants ---

export const WHATSAPP_CONVERSATION_API_PATH =
  '/api/auxiliary/skillset/ability/chatbotkit/integration/whatsapp'

export const START_CONVERSATION_HANDLER_NAME = 'startConversation'

// --- Schemas ---

const startConversationSchema = z.object({
  whatsappIntegrationId: z
    .string()
    .min(1)
    .describe('The ID of the WhatsApp integration to use'),
  to: z
    .string()
    .min(1)
    .describe(
      'The recipient phone number in international format (e.g. 14155238886)'
    ),
  text: z
    .string()
    .min(1)
    .describe('The initial message text to send to the recipient'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

export type StartConversationSchema = z.infer<typeof startConversationSchema>

// --- Handlers ---

async function startConversation(
  session: Session,
  parameters: z.infer<typeof startConversationSchema>,
  headers: Headers
) {
  debug('start conversation', { parameters, headers }).log(
    'api.auxiliary.skillset.ability.chatbotkit.integration.whatsapp.startConversation'
  )

  const { whatsappIntegrationId, to, text, context } = parameters

  const conversationId = getHeader(headers, 'x-chatbotkit-conversation-id')

  // Fetch the WhatsApp integration and verify user ownership

  const whatsappIntegration =
    await prisma.whatsappIntegration.findUniqueByIdentifier(
      session.user,
      whatsappIntegrationId,
      {
        select: {
          id: true,
          userId: true,
          accessToken: true,
          phoneNumberId: true,
        },
      }
    )

  if (!whatsappIntegration) {
    throw new UserInputError('WhatsApp integration not found')
  }

  if (whatsappIntegration.userId !== session.user.id) {
    throw new UserInputError('Not authorized to use this WhatsApp integration')
  }

  if (!whatsappIntegration.accessToken) {
    throw new UserInputError(
      'WhatsApp integration does not have an access token'
    )
  }

  if (!whatsappIntegration.phoneNumberId) {
    throw new UserInputError(
      'WhatsApp integration does not have a phone number ID configured'
    )
  }

  // Start conversation using the integration queue system
  // @note this will send the initial message and create a conversation

  await sendEvent(whatsappIntegration.id, {
    type: 'initiate',
    payload: {
      to,

      text,

      ...(context
        ? {
            context: {
              linkedConversationId: conversationId,
              linkedReason: 'Started',

              text: context,
            },
          }
        : {}),
    },
  })

  return {
    success: true,
    to,
  }
}

export default authenticatedMultiHandler({
  [START_CONVERSATION_HANDLER_NAME]: {
    schema: startConversationSchema,
    fn: startConversation,
  },
})
