
export const FAILURE_CODE_HEADER_NAME = 'X-Failure-Code'

export const OK_STATUS = 200
export const CREATED_STATUS = 201
export const NO_CONTENT_STATUS = 204
export const NOT_MODIFIED_STATUS = 304
export const BAD_REQUEST_STATUS = 400
export const NOT_AUTHENTICATED_STATUS = 401
export const NO_SUBSCRIPTION_STATUS = 402
export const NOT_AUTHORIZED_STATUS = 403
export const NOT_FOUND_STATUS = 404
export const METHOD_NOT_ALLOWED_STATUS = 405
export const TIMEOUT_STATUS = 408
export const CONFLICT_STATUS = 409
export const UNPROCESSABLE_ENTITY_STATUS = 422
export const TOO_MANY_REQUESTS_STATUS = 429
export const LIMITS_REACHED_STATUS = 429
export const INTERNAL_SERVER_ERROR_STATUS = 500
export const NOT_IMPLEMENTED_STATUS = 501
export const BAD_GATEWAY_STATUS = 502
export const SERVICE_UNAVAILABLE_STATUS = 503
export const GATEWAY_TIMEOUT_STATUS = 504

export const OK_MESSAGE = 'OK'
export const CREATED_MESSAGE = 'Created'
export const NO_CONTENT_MESSAGE = 'No content'
export const NOT_MODIFIED_MESSAGE = 'Not modified'
export const BAD_REQUEST_MESSAGE = 'Bad request'
export const NOT_AUTHENTICATED_MESSAGE = 'Not authenticated'
export const NOT_AUTHORIZED_MESSAGE = 'Not authorized'
export const NO_SUBSCRIPTION_MESSAGE = 'No subscription'
export const NOT_FOUND_MESSAGE = 'Not found'
export const METHOD_NOT_ALLOWED_MESSAGE = 'Method not allowed'
export const TIMEOUT_MESSAGE = 'Timeout'
export const CONFLICT_MESSAGE = 'Conflict'
export const UNPROCESSABLE_ENTITY_STATUS_MESSAGE = 'Unprocessable entity'
export const TOO_MANY_REQUESTS_MESSAGE = 'Too many requests'
export const LIMITS_REACHED_MESSAGE = 'Limits reached'
export const INTERNAL_SERVER_ERROR_MESSAGE = 'Internal server error'
export const NOT_IMPLEMENTED_MESSAGE = 'Not implemented'
export const BAD_GATEWAY_MESSAGE = 'Bad gateway'
export const SERVICE_UNAVAILABLE_MESSAGE = 'Service unavailable'
export const GATEWAY_TIMEOUT_MESSAGE = 'Gateway timeout'

export const OK_CODE = 'OK'
export const CREATED_CODE = 'CREATED'
export const NO_CONTENT_CODE = 'NO_CONTENT'
export const NOT_MODIFIED_CODE = 'NOT_MODIFIED'
export const BAD_REQUEST_CODE = 'BAD_REQUEST'
export const NOT_AUTHENTICATED_CODE = 'NOT_AUTHENTICATED'
export const NOT_AUTHORIZED_CODE = 'NOT_AUTHORIZED'
export const NO_SUBSCRIPTION_CODE = 'NO_SUBSCRIPTION'
export const NOT_FOUND_CODE = 'NOT_FOUND'
export const METHOD_NOT_ALLOWED_CODE = 'METHOD_NOT_ALLOWED'
export const TIMEOUT_CODE = 'TIMEOUT'
export const CONFLICT_CODE = 'CONFLICT'
export const UNPROCESSABLE_ENTITY_CODE = 'UNPROCESSABLE_ENTITY'
export const TOO_MANY_REQUESTS_CODE = 'TOO_MANY_REQUESTS'
export const LIMITS_REACHED_CODE = 'LIMITS_REACHED'
export const INTERNAL_SERVER_ERROR_CODE = 'INTERNAL_SERVER_ERROR'
export const NOT_IMPLEMENTED_CODE = 'NOT_IMPLEMENTED'
export const BAD_GATEWAY_CODE = 'BAD_GATEWAY'
export const SERVICE_UNAVAILABLE_CODE = 'SERVICE_UNAVAILABLE'
export const GATEWAY_TIMEOUT_CODE = 'GATEWAY_TIMEOUT'

export const statusToMessageMap = {
  [OK_STATUS]: OK_MESSAGE,
  [CREATED_STATUS]: CREATED_MESSAGE,
  [NO_CONTENT_STATUS]: NO_CONTENT_MESSAGE,
  [NOT_MODIFIED_STATUS]: NOT_MODIFIED_MESSAGE,
  [BAD_REQUEST_STATUS]: BAD_REQUEST_MESSAGE,
  [NOT_AUTHENTICATED_STATUS]: NOT_AUTHENTICATED_MESSAGE,
  [NOT_AUTHORIZED_STATUS]: NOT_AUTHORIZED_MESSAGE,
  [NO_SUBSCRIPTION_STATUS]: NO_SUBSCRIPTION_MESSAGE,
  [NOT_FOUND_STATUS]: NOT_FOUND_MESSAGE,
  [METHOD_NOT_ALLOWED_STATUS]: METHOD_NOT_ALLOWED_MESSAGE,
  [TIMEOUT_STATUS]: TIMEOUT_MESSAGE,
  [CONFLICT_STATUS]: CONFLICT_MESSAGE,
  [UNPROCESSABLE_ENTITY_STATUS]: UNPROCESSABLE_ENTITY_STATUS_MESSAGE,
  [TOO_MANY_REQUESTS_STATUS]: TOO_MANY_REQUESTS_MESSAGE,
  // [LIMITS_REACHED_STATUS]: LIMITS_REACHED_MESSAGE,  // disable because duplicate status
  [INTERNAL_SERVER_ERROR_STATUS]: INTERNAL_SERVER_ERROR_MESSAGE,
  [NOT_IMPLEMENTED_STATUS]: NOT_IMPLEMENTED_MESSAGE,
  [BAD_GATEWAY_STATUS]: BAD_GATEWAY_MESSAGE,
  [SERVICE_UNAVAILABLE_STATUS]: SERVICE_UNAVAILABLE_MESSAGE,
  [GATEWAY_TIMEOUT_STATUS]: GATEWAY_TIMEOUT_MESSAGE,
}

export const statusToCodeMap = {
  [OK_STATUS]: OK_CODE,
  [CREATED_STATUS]: CREATED_CODE,
  [NO_CONTENT_STATUS]: NO_CONTENT_CODE,
  [NOT_MODIFIED_STATUS]: NOT_MODIFIED_CODE,
  [BAD_REQUEST_STATUS]: BAD_REQUEST_CODE,
  [NOT_AUTHENTICATED_STATUS]: NOT_AUTHENTICATED_CODE,
  [NOT_AUTHORIZED_STATUS]: NOT_AUTHORIZED_CODE,
  [NO_SUBSCRIPTION_STATUS]: NO_SUBSCRIPTION_CODE,
  [NOT_FOUND_STATUS]: NOT_FOUND_CODE,
  [METHOD_NOT_ALLOWED_STATUS]: METHOD_NOT_ALLOWED_CODE,
  [TIMEOUT_STATUS]: TIMEOUT_CODE,
  [CONFLICT_STATUS]: CONFLICT_CODE,
  [UNPROCESSABLE_ENTITY_STATUS]: UNPROCESSABLE_ENTITY_CODE,
  [TOO_MANY_REQUESTS_STATUS]: TOO_MANY_REQUESTS_CODE,
  // [LIMITS_REACHED_STATUS]: LIMITS_REACHED_CODE, // disabled because duplicate status
  [INTERNAL_SERVER_ERROR_STATUS]: INTERNAL_SERVER_ERROR_CODE,
  [NOT_IMPLEMENTED_STATUS]: NOT_IMPLEMENTED_CODE,
  [BAD_GATEWAY_STATUS]: BAD_GATEWAY_CODE,
  [SERVICE_UNAVAILABLE_STATUS]: SERVICE_UNAVAILABLE_CODE,
  [GATEWAY_TIMEOUT_STATUS]: GATEWAY_TIMEOUT_CODE,
}

export const messageToCodeMap = {
  [OK_MESSAGE]: OK_CODE,
  [CREATED_MESSAGE]: CREATED_CODE,
  [NO_CONTENT_MESSAGE]: NO_CONTENT_CODE,
  [NOT_MODIFIED_MESSAGE]: NOT_MODIFIED_CODE,
  [BAD_REQUEST_MESSAGE]: BAD_REQUEST_CODE,
  [NOT_AUTHENTICATED_MESSAGE]: NOT_AUTHENTICATED_CODE,
  [NOT_AUTHORIZED_MESSAGE]: NOT_AUTHORIZED_CODE,
  [NO_SUBSCRIPTION_MESSAGE]: NO_SUBSCRIPTION_CODE,
  [NOT_FOUND_MESSAGE]: NOT_FOUND_CODE,
  [METHOD_NOT_ALLOWED_MESSAGE]: METHOD_NOT_ALLOWED_CODE,
  [TIMEOUT_MESSAGE]: TIMEOUT_CODE,
  [CONFLICT_MESSAGE]: CONFLICT_CODE,
  [UNPROCESSABLE_ENTITY_STATUS_MESSAGE]: UNPROCESSABLE_ENTITY_CODE,
  [TOO_MANY_REQUESTS_MESSAGE]: TOO_MANY_REQUESTS_CODE,
  [LIMITS_REACHED_MESSAGE]: LIMITS_REACHED_CODE,
  [INTERNAL_SERVER_ERROR_MESSAGE]: INTERNAL_SERVER_ERROR_CODE,
  [NOT_IMPLEMENTED_MESSAGE]: NOT_IMPLEMENTED_CODE,
  [BAD_GATEWAY_MESSAGE]: BAD_GATEWAY_CODE,
  [SERVICE_UNAVAILABLE_MESSAGE]: SERVICE_UNAVAILABLE_CODE,
  [GATEWAY_TIMEOUT_MESSAGE]: GATEWAY_TIMEOUT_CODE,
}

export const codeToStatusMap = {
  [OK_CODE]: OK_STATUS,
  [CREATED_CODE]: CREATED_STATUS,
  [NO_CONTENT_CODE]: NO_CONTENT_STATUS,
  [NOT_MODIFIED_CODE]: NOT_MODIFIED_STATUS,
  [BAD_REQUEST_CODE]: BAD_REQUEST_STATUS,
  [NOT_AUTHENTICATED_CODE]: NOT_AUTHENTICATED_STATUS,
  [NOT_AUTHORIZED_CODE]: NOT_AUTHORIZED_STATUS,
  [NO_SUBSCRIPTION_CODE]: NO_SUBSCRIPTION_STATUS,
  [NOT_FOUND_CODE]: NOT_FOUND_STATUS,
  [METHOD_NOT_ALLOWED_CODE]: METHOD_NOT_ALLOWED_STATUS,
  [TIMEOUT_CODE]: TIMEOUT_STATUS,
  [CONFLICT_CODE]: CONFLICT_STATUS,
  [UNPROCESSABLE_ENTITY_CODE]: UNPROCESSABLE_ENTITY_STATUS,
  [TOO_MANY_REQUESTS_CODE]: TOO_MANY_REQUESTS_STATUS,
  [LIMITS_REACHED_CODE]: LIMITS_REACHED_STATUS,
  [INTERNAL_SERVER_ERROR_CODE]: INTERNAL_SERVER_ERROR_STATUS,
  [NOT_IMPLEMENTED_CODE]: NOT_IMPLEMENTED_STATUS,
  [BAD_GATEWAY_CODE]: BAD_GATEWAY_STATUS,
  [SERVICE_UNAVAILABLE_CODE]: SERVICE_UNAVAILABLE_STATUS,
  [GATEWAY_TIMEOUT_CODE]: GATEWAY_TIMEOUT_STATUS,
}

export const knownExpectedCodes = [
  CREATED_CODE,
  NOT_MODIFIED_CODE,
  BAD_REQUEST_CODE,
  NOT_AUTHENTICATED_CODE,
  NOT_AUTHORIZED_CODE,
  NO_SUBSCRIPTION_CODE,
  NOT_FOUND_CODE,
  METHOD_NOT_ALLOWED_CODE,
  CONFLICT_MESSAGE,
  TIMEOUT_CODE,
  CONFLICT_CODE,
  UNPROCESSABLE_ENTITY_CODE,
  TOO_MANY_REQUESTS_CODE,
  LIMITS_REACHED_CODE,
]
