// @ts-check
import {
  formatIntegrationInbox,
  formatIntegrationMessageId,
  sendEmailAction,
} from '@chatbotkit-dev/email'

import messages from '@/config/messages'

import prisma from '@/prisma/client'

import { makeActivityMessagePair } from '@/lib/activity'
import { getConversationDetails } from '@/lib/bot.conversation'
import {
  createContactFingerprint,
  ensureTrustedContact,
} from '@/lib/contact.create'
import { setContextUser } from '@/lib/context.store'
import {
  makeConversationAttachmentUploadActivityMessages,
  uploadConversationAttachmentFromURL,
} from '@/lib/conversation.attachment'
import { createConversation } from '@/lib/conversation.create'
import { getStatefulConversationEngine } from '@/lib/conversation.engine'
import { hasConversation } from '@/lib/conversation.find'
import debug from '@/lib/debug'
import { captureInputError } from '@/lib/error'
import { setupFrontendHostContext } from '@/lib/integration.context'
import { accountConversationalLimitsOk } from '@/lib/limit.core'
import { logEvent } from '@/lib/log'
import { toHtml } from '@/lib/md.convert'
import memcache from '@/lib/memcache'
import { allocateOrder, messagingSupersede } from '@/lib/messaging.supersede'
import queue from '@/lib/queue'
import { withQueueHandlerBounded } from '@/lib/queue2'
import { updateSessionStore } from '@/lib/session.context'
import { resolveSessionDuration } from '@/lib/session.duration'
import { getMaxFileSize } from '@/lib/user.limits'
import { userToSessionUser } from '@/lib/user.session'
import { parseAsync } from '@/lib/zod.schema'

import { doSetup } from '@/pages/api/v1/integration/email/[emailIntegrationId]/setup'

import { z } from 'zod'

export const EMAIL_CONTACT_NAMESPACE = '128c62b7-a418-41ca-a65d-d53549f8fc75' // @note do not change

export const INTERACT_EVENT_TYPE = 'interact'
export const INITIATE_EVENT_TYPE = 'initiate'
export const SEND_EVENT_TYPE = 'send'
export const SETUP_EVENT_TYPE = 'setup'

/**
 * @typedef {z.infer<typeof InteractPayloadSchema>} InteractPayload
 */
export const InteractPayloadSchema = z.object({
  messageId: z.string().optional(),
  inReplyTo: z.string().optional(),
  to: z.string(),
  from: z.object({
    name: z.string().optional(),
    email: z.string(),
  }),
  subject: z.string(),
  message: z.string(),
  attachments: z
    .array(
      z.object({
        name: z.string(),
        size: z.number(),
        type: z.string(),
        data: z.object({
          url: z.string(),
        }),
      })
    )
    .optional(),
  meta: z.record(z.string()).optional(),

  // @note per-sender monotonic order allocated on the webhook path (see
  // getEmailSupersedeSessionKey / allocateOrder). Threaded through here so the
  // handler can detect it has been superseded by a newer email. Optional for
  // backward-compat with events enqueued before supersede was wired.
  order: z.number().optional(),
})

/**
 * Session key for the supersede + soft-yield mechanism - keyed on the SENDER,
 * not the email thread. Email has no stable per-thread key available on the
 * webhook path (the payload carries only messageId/inReplyTo, no References, and
 * the conversation is resolved by walking the reply chain in the handler), so we
 * treat all rapid emails from one sender as one steerable train of thought. The
 * trade-off: two unrelated threads from the same sender arriving within the
 * bot's response window would cross-supersede (rare; the later wins).
 *
 * @param {string} emailIntegrationId
 * @param {string} email
 * @returns {string}
 */
export function getEmailSupersedeSessionKey(emailIntegrationId, email) {
  return `email-supersede-${emailIntegrationId}-${email}`
}

/**
 * @typedef {z.infer<typeof SetupPayloadSchema>} SetupPayload
 */
export const SetupPayloadSchema = z.object({
  // pass
})

/**
 * @typedef {z.infer<typeof SendPayloadSchema>} SendPayload
 */
export const SendPayloadSchema = z.object({
  email: z.string().email().describe('The recipient email address'),
  subject: z.string().min(1).describe('The email subject line'),
  text: z.string().min(1).describe('The initial message text to send'),
  context: z
    .string()
    .optional()
    .describe(
      'Optional context about the recipient or conversation, typically generated by the agent'
    ),
})

/**
 * @typedef {z.infer<typeof InitiatePayloadSchema>} InitiatePayload
 */
export const InitiatePayloadSchema = z.object({
  email: z.string().email().describe('The recipient email address'),
  subject: z.string().min(1).optional().describe('The email subject line'),
  text: z
    .string()
    .min(1)
    .describe('The instruction to use to initiate the conversation'),
})

/**
 * @param {{
 *   integration: import('@/prisma/types').EmailIntegration & { bot?: import('@/prisma/types').Bot | null},
 *   name?: string,
 *   email: string,
 *   messageId?: string,
 *   inReplyTo?: string
 * }} options
 * @returns {Promise<string>}
 */
export async function getConversationSessionId({
  integration,
  name,
  email,
  messageId,
  inReplyTo,
}) {
  const { persist, ttlSecs } = resolveSessionDuration(
    integration.sessionDuration
  )

  // derive conversationId from messageId

  const messageIdSessionKey = `email-session-${integration.id}-${email}-${
    messageId || 'default'
  }`

  // @note when `persist` is false (sessionDuration === 0, "no session") we
  // never look up or store the mapping, so every email starts a fresh
  // conversation.
  let conversationId = persist ? await memcache.get(messageIdSessionKey) : null

  if (persist && !conversationId && inReplyTo) {
    const inReplyToSessionKey = `email-session-${integration.id}-${email}-${inReplyTo}`

    conversationId = await memcache.get(inReplyToSessionKey)
  }

  if (!conversationId || !(await hasConversation(conversationId))) {
    let contactId

    {
      if (integration.contactCollection) {
        const contact = await ensureTrustedContact(
          { id: integration.userId },
          {
            name: name,
            email: email,

            meta: {
              app: 'email',
            },
          },
          createContactFingerprint(EMAIL_CONTACT_NAMESPACE, [email])
        )

        contactId = contact.id
      }
    }

    const { id: cid } = await createConversation(integration.userId, {
      contactId,

      ...getConversationDetails({ bot: integration.bot }),

      meta: {
        app: 'email',

        email: {
          integrationId: integration.id,
        },
      },
    })

    conversationId = cid
  }

  if (persist) {
    await memcache.set(messageIdSessionKey, conversationId, {
      ex: ttlSecs,
    })
  }

  return conversationId
}

/**
 * @param {{
 *   integration: Pick<import('@/prisma/types').EmailIntegration, 'attachments' | 'userId'>,
 *   email: string,
 *   userInfo?: import('@/lib/conversation.features').UserInfoFeature['options'],
 *   signal?: AbortSignal,
 *   markSignals?: AbortSignal[],
 *   yieldSignal?: AbortSignal
 * }} options
 */
export function getEmailConversationEngineOptions({
  integration,
  email,
  userInfo,
  signal,
  markSignals,
  yieldSignal,
}) {
  return {
    signal,

    // @note fire-once per-mark signals from the queue monitor; the engine's
    // `timeoutMarks` feature listens to these. NOT cancellation signals

    markSignals,

    // @note cooperative soft-yield: tripped when a newer email from the same
    // sender supersedes this turn, so the engine stops at its next iteration
    // boundary instead of finishing a reply that would be thrown away. Only the
    // interact flow sets this; initiate/send leave it undefined.

    yieldSignal,

    backstoryExtra: `NB: This conversation is happening over email. The user's email address is ${email}.`,

    features: [
      // @note surface who sent the current message to the model for this turn
      // only - the userInfo feature injects it as a soft activity message and
      // never persists it. Only inbound (interact) flows carry a sender.

      ...(userInfo
        ? [{ name: 'userInfo', options: userInfo }]
        : /** @type {any[]} */ ([])),

      // @note record a checkpoint activity into the conversation each time the
      // queue handler crosses a timeout-budget mark (driven by markSignals
      // above), visible to the model on the next turn

      { name: 'timeoutMarks' },

      // @note auth is required to prompt the model to ask the user to
      // re-authenticate any secrets that are missing or expired

      { name: 'auth' },

      // @note time gives the model reliable current date/time awareness
      // instead of guessing from stale training data

      { name: 'time' },

      // @note if attachments are enabled, the model should have the ability
      // to read them from the context and reference them in its responses

      ...(integration.attachments
        ? [{ name: 'attachments' }]
        : /** @type {any[]} */ ([])),
    ],

    userId: integration.userId,
  }
}

/**
 * @typedef {{
 *   type: typeof INTERACT_EVENT_TYPE,
 *   payload: InteractPayload
 * }} InteractEvent
 *
 * @param {string} emailIntegrationId
 * @param {InteractPayload} payload
 * @returns {Promise<void>}
 */
export async function handleInteractEvent(
  emailIntegrationId,
  payload,
  context
) {
  debug(`interact`, { emailIntegrationId, payload })

  const integration = await prisma.emailIntegration.findUnique({
    where: {
      id: emailIntegrationId,
    },

    include: {
      user: true, // @note super important

      bot: true, // @note super important
    },
  })

  if (!integration) {
    debug(`skipping - integration not found`, { emailIntegrationId }).log(
      'integration.email.queue.handleInteractEvent'
    )

    return
  }

  if (!integration.bot) {
    debug(`skipping - no bot configured`).log(
      'integration.email.queue.handleInteractEvent'
    )

    return
  }

  if (!(await accountConversationalLimitsOk(integration.user))) {
    debug(`skipping - limits exceeded`, { emailIntegrationId }).log(
      'integration.email.queue.handleInteractEvent'
    )

    // @note the account is over its usage limits - send a pre-canned reply so
    // the sender gets a visible signal instead of silence. Best-effort: a
    // failed send must not mask the underlying limit condition.
    try {
      const text = messages.limitsReachedReply
      const html = await toHtml(text)

      await sendEmailAction({
        subject: payload.subject || 'Re:',
        content: { text, html },
        name: integration.name,
        from: payload.to,
        to: payload.from.email,
        messageId: payload.messageId,
      })
    } catch (error) {
      debug(`limit reply send failed`, { error }).log(
        'integration.email.queue.handleInteractEvent'
      )
    }

    return
  }

  if (integration.user) {
    updateSessionStore({
      user: userToSessionUser(integration.user),
    })

    setContextUser(integration.user)

    await setupFrontendHostContext(integration.user)
  }

  const conversationId = await getConversationSessionId({
    integration,
    name: payload.from.name,
    email: payload.from.email,
    messageId: payload.messageId,
    inReplyTo: payload.inReplyTo,
  })

  // @note supersede + soft-yield: a newer email from the same sender (a rapid
  // follow-up) should steer this turn rather than queue a second reply. Only
  // meaningful when sessions persist and the webhook allocated an order (events
  // enqueued before supersede was wired carry none).

  const { persist } = resolveSessionDuration(integration.sessionDuration)

  const superseding = persist && payload.order != null

  const supersede = messagingSupersede(
    getEmailSupersedeSessionKey(emailIntegrationId, payload.from.email),
    payload.order ?? 0
  )

  const watch = superseding ? supersede.watch() : null

  const engine = await getStatefulConversationEngine({
    conversationId: conversationId,

    options: getEmailConversationEngineOptions({
      integration,
      email: payload.from.email,
      userInfo: {
        name: payload.from.name,
        email: payload.from.email,
        externalId: payload.from.email,
        source: 'email',
      },
      signal: context?.signal,
      markSignals: context?.markSignals,
      yieldSignal: watch?.yieldSignal,
    }),
  })

  try {
    if (payload.attachments?.length) {
      const maxFileSize = await getMaxFileSize(integration.user)

      const newMessages = (
        await Promise.all(
          payload.attachments.map(async (attachment) => {
            const { attachmentId, name, type } =
              await uploadConversationAttachmentFromURL(
                conversationId,
                attachment.data.url,
                {},
                {
                  maxSize: maxFileSize,
                }
              )

            const {
              request: uploadRequestActivityMessage,
              response: uploadResponseActivityMessage,
            } = makeConversationAttachmentUploadActivityMessages({
              id: attachmentId,
              name: name,
              type: type,
            })

            return [uploadRequestActivityMessage, uploadResponseActivityMessage]
          })
        )
      ).flat()

      await engine.addMessages(newMessages)
    }

    await engine.send(payload.message)

    // @note superseded before generation - the message is now in the
    // conversation, so skip producing a reply that the latest email's handler
    // will coalesce. Cheap guard that avoids a doomed model call.
    if (superseding && (await supersede.isSuperseded())) {
      debug(`superseded before generation - skipping reply`).log(
        'integration.email.queue.handleInteractEvent'
      )

      return
    }

    // @todo provide indication that the bot is typing

    const { text } = await engine.receive()

    // @note the engine soft-yielded mid-turn because a newer email superseded
    // this one; its partial progress is stored, so skip the send and let the
    // latest email's handler produce the reply the user actually sees.
    if (watch?.didYield()) {
      debug(`yielded to a newer email - skipping send`).log(
        'integration.email.queue.handleInteractEvent'
      )

      return
    }

    const html = await toHtml(text)

    await sendEmailAction({
      subject: payload.subject || 'Re:',
      content: { text, html },
      name: integration.name,
      from: payload.to,
      to: payload.from.email,
      messageId: payload.messageId,
    })

    await logEvent({
      user: { id: integration.userId },
      name: 'Email Sent',
      description: `The email was sent to the recipient.`,
      type: 'integration.email.sent',
      relations: {
        emailIntegrationId: integration.id,
        conversationId: conversationId,
      },
      meta: {
        from: payload.to,
        to: payload.from.email,
        messageId: payload.messageId,
      },
    })
  } finally {
    // @note stop watching the sender channel and tear down its subscription;
    // the turn is over (sent, yielded, or errored).
    if (watch) {
      await watch.dispose()
    }

    await engine.dispose()
  }
}

/**
 * @typedef {{
 *   type: typeof SETUP_EVENT_TYPE,
 *   payload: SetupPayload
 * }} SetupEvent
 *
 * @param {string} emailIntegrationId
 * @param {SetupPayload} payload
 */
export async function handleSetupEvent(emailIntegrationId, payload) {
  debug('setup', { emailIntegrationId, payload })

  const integration = await prisma.emailIntegration.findUnique({
    where: {
      id: emailIntegrationId,
    },

    include: {
      user: true,
    },
  })

  if (!integration) {
    debug(`skipping - integration not found`, { emailIntegrationId }).log(
      'integration.email.queue.handleSetupEvent'
    )

    return
  }

  if (integration.user) {
    updateSessionStore({
      user: userToSessionUser(integration.user),
    })

    setContextUser(integration.user)

    await setupFrontendHostContext(integration.user)
  }

  await doSetup(integration)
}

/**
 * @typedef {{
 *   type: typeof SEND_EVENT_TYPE,
 *   payload: SendPayload
 * }} SendEvent
 *
 * Handles the send event - sends an initial email to a recipient
 * and creates a conversation so that subsequent email replies are tracked.
 *
 * This is used when the outbound text has already been authored.
 *
 * @param {string} emailIntegrationId
 * @param {SendPayload} payload
 * @returns {Promise<void>}
 */
export async function handleSendEvent(emailIntegrationId, payload, context) {
  debug('send', { emailIntegrationId, payload }).log(
    'integration.email.queue.handleSendEvent'
  )

  const integration = await prisma.emailIntegration.findUnique({
    where: {
      id: emailIntegrationId,
    },

    include: {
      user: true,
      bot: true,
    },
  })

  if (!integration) {
    debug(`skipping - integration not found`, { emailIntegrationId }).log(
      'integration.email.queue.handleSendEvent'
    )

    return
  }

  if (!integration.bot) {
    debug(`skipping - no bot configured`).log(
      'integration.email.queue.handleSendEvent'
    )

    return
  }

  if (!(await accountConversationalLimitsOk(integration.user))) {
    debug(`skipping - limits exceeded`, { emailIntegrationId }).log(
      'integration.email.queue.handleSendEvent'
    )

    return
  }

  if (integration.user) {
    updateSessionStore({
      user: userToSessionUser(integration.user),
    })

    setContextUser(integration.user)

    await setupFrontendHostContext(integration.user)
  }

  // @note generate a unique messageId for this initiated email so that when
  // the recipient replies, we can link it back to this conversation via the
  // In-Reply-To header
  const messageId = formatIntegrationMessageId(integration.id)

  // Create a conversation and get/create the session
  const conversationId = await getConversationSessionId({
    integration,
    email: payload.email,
    messageId,
  })

  const { persist, ttlSecs } = resolveSessionDuration(
    integration.sessionDuration
  )

  // @note store the session with messageId so replies can find this conversation
  const messageIdSessionKey = `email-session-${integration.id}-${payload.email}-${messageId}`

  if (persist) {
    await memcache.set(messageIdSessionKey, conversationId, {
      ex: ttlSecs,
    })
  }

  // Get the conversation engine to record the bot's message
  const engine = await getStatefulConversationEngine({
    conversationId,

    options: getEmailConversationEngineOptions({
      integration,
      email: payload.email,
      signal: context?.signal,
      markSignals: context?.markSignals,
    }),
  })

  try {
    // Record the bot's outgoing message in the conversation
    // @note if context is provided, add it as an activity so the bot has
    // background information about the recipient for future interactions
    const contextMessages = payload.context
      ? makeActivityMessagePair(
          '_getEmailContext',
          { email: payload.email },
          { context: payload.context }
        )
      : []

    await engine.addMessages([
      ...contextMessages,
      {
        type: 'bot',
        text: payload.text,
      },
    ])

    // Send the email
    const html = await toHtml(payload.text)

    await sendEmailAction({
      subject: payload.subject,
      content: { text: payload.text, html },
      name: integration.name,
      from: formatIntegrationInbox(integration.id),
      to: payload.email,
      messageId,
    })

    await logEvent({
      user: { id: integration.userId },
      name: 'Email Sent',
      description: `The email was sent to the recipient.`,
      type: 'integration.email.sent',
      relations: {
        emailIntegrationId: integration.id,
        conversationId: conversationId,
      },
      meta: {
        from: formatIntegrationInbox(integration.id),
        to: payload.email,
        subject: payload.subject,
        messageId,
      },
    })
  } finally {
    await engine.dispose()
  }
}

/**
 * @typedef {{
 *   type: typeof INITIATE_EVENT_TYPE,
 *   payload: InitiatePayload
 * }} InitiateEvent
 *
 * Handles the initiate event - starts a conversation from an instruction and
 * lets the agent author the initial email before it is sent.
 *
 * @param {string} emailIntegrationId
 * @param {InitiatePayload} payload
 * @returns {Promise<void>}
 */
export async function handleInitiateEvent(
  emailIntegrationId,
  payload,
  context
) {
  debug('initiate', { emailIntegrationId, payload }).log(
    'integration.email.queue.handleInitiateEvent'
  )

  const integration = await prisma.emailIntegration.findUnique({
    where: {
      id: emailIntegrationId,
    },

    include: {
      user: true,
      bot: true,
    },
  })

  if (!integration) {
    debug(`skipping - integration not found`, { emailIntegrationId }).log(
      'integration.email.queue.handleInitiateEvent'
    )

    return
  }

  if (!integration.bot) {
    debug(`skipping - no bot configured`).log(
      'integration.email.queue.handleInitiateEvent'
    )

    return
  }

  if (!(await accountConversationalLimitsOk(integration.user))) {
    debug(`skipping - limits exceeded`, { emailIntegrationId }).log(
      'integration.email.queue.handleInitiateEvent'
    )

    return
  }

  if (integration.user) {
    updateSessionStore({
      user: userToSessionUser(integration.user),
    })

    setContextUser(integration.user)

    await setupFrontendHostContext(integration.user)
  }

  const messageId = formatIntegrationMessageId(integration.id)

  const conversationId = await getConversationSessionId({
    integration,
    email: payload.email,
    messageId,
  })

  const engine = await getStatefulConversationEngine({
    conversationId,

    options: getEmailConversationEngineOptions({
      integration,
      email: payload.email,
      signal: context?.signal,
      markSignals: context?.markSignals,
    }),
  })

  try {
    await engine.send(payload.text, { type: 'instruction' })

    const { text } = await engine.receive()

    const html = await toHtml(text)

    await sendEmailAction({
      subject: payload.subject || 'Re:',
      content: { text, html },
      name: integration.name,
      from: formatIntegrationInbox(integration.id),
      to: payload.email,
      messageId,
    })

    await logEvent({
      user: { id: integration.userId },
      name: 'Email Sent',
      description: `The email was sent to the recipient.`,
      type: 'integration.email.sent',
      relations: {
        emailIntegrationId: integration.id,
        conversationId: conversationId,
      },
      meta: {
        from: formatIntegrationInbox(integration.id),
        to: payload.email,
        messageId,
      },
    })
  } finally {
    await engine.dispose()
  }
}

/**
 * @param {string} emailIntegrationId
 * @param {InteractEvent|SetupEvent|SendEvent|InitiateEvent} event
 * @returns {Promise<void>}
 */
export async function sendEvent(emailIntegrationId, event) {
  switch (true) {
    case event.type === INTERACT_EVENT_TYPE: {
      await parseAsync(InteractPayloadSchema, event.payload, captureInputError)

      break
    }

    case event.type === INITIATE_EVENT_TYPE: {
      await parseAsync(InitiatePayloadSchema, event.payload, captureInputError)

      break
    }

    case event.type === SEND_EVENT_TYPE: {
      await parseAsync(SendPayloadSchema, event.payload, captureInputError)

      break
    }

    case event.type === SETUP_EVENT_TYPE: {
      await parseAsync(SetupPayloadSchema, event.payload, captureInputError)

      break
    }
  }

  if (event.type === INTERACT_EVENT_TYPE) {
    // @note allocate a per-sender order and nudge any in-flight handler for an
    // earlier email from the same sender so it can soft-yield; thread the order
    // into the (already-validated) payload and serialize the dispatch per sender
    // so handlers run one at a time.
    const sessionKey = getEmailSupersedeSessionKey(
      emailIntegrationId,
      event.payload.from.email
    )

    event.payload.order = await allocateOrder(sessionKey)

    await queue(
      `/api/v1/integration/email/${emailIntegrationId}/queue`,
      event,
      { flow: { key: sessionKey, parallel: 1 } }
    )

    return
  }

  await queue(
    `/api/v1/integration/email/${emailIntegrationId}/queue`,
    event,
    {}
  )
}

/**
 */
export default withQueueHandlerBounded('emailIntegrationId', {
  [INTERACT_EVENT_TYPE]: {
    handler: handleInteractEvent,
    schema: InteractPayloadSchema,
  },
  [INITIATE_EVENT_TYPE]: {
    handler: handleInitiateEvent,
    schema: InitiatePayloadSchema,
  },
  [SEND_EVENT_TYPE]: {
    handler: handleSendEvent,
    schema: SendPayloadSchema,
  },
  [SETUP_EVENT_TYPE]: {
    handler: handleSetupEvent,
    schema: SetupPayloadSchema,
  },
})
