export const MAX_REQUEST_DURATION_MS = 800_000 // 13 minutes

export const REQUEST_ABORT_GRACE_PERIOD_MS = 30_000 // 30 seconds

export const REQUEST_SOFT_ABORT_TIMEOUT_MS =
  MAX_REQUEST_DURATION_MS - REQUEST_ABORT_GRACE_PERIOD_MS
