// @note one-shot provisioning for the local Garage store, run by the
// garage-init compose service against Garage's admin API: assign the
// single-node layout, provision the access key, create one bucket per
// storage scope and grant the key access to each. Idempotent - every step
// checks before it acts, so the stack restarts cleanly.
//
// The access key comes from STORAGE_ACCESS_KEY_ID / STORAGE_SECRET_ACCESS_KEY
// when set; otherwise one is generated by Garage on first boot and persisted
// in /data (the volume shared with the application, whose entrypoint sources
// it - see docker/entrypoint.sh).
//
// The bucket list mirrors the scopes in @chatbotkit-dev/storage; the compose
// file carries the matching *_S3_BUCKET_NAME variables.
//
// Browsers upload and download through presigned URLs straight against the
// store, so every bucket also gets a CORS rule. Garage only takes CORS over
// the S3 API, hence the SigV4 signing below.
import { createHash, createHmac } from 'node:crypto'
import { chownSync, readFileSync, writeFileSync } from 'node:fs'

const base = process.env.GARAGE_ADMIN_URL
const token = process.env.GARAGE_ADMIN_TOKEN

const s3Url = process.env.GARAGE_S3_URL || 'http://garage:3900'
const s3Region = process.env.GARAGE_S3_REGION || 'garage'

// @note presigned URLs are the access control; the rule only lets the
// browser make the call. Narrow it for a store reachable beyond the host
const corsOrigins = (process.env.STORAGE_CORS_ORIGINS || '*')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean)

let accessKeyId = process.env.STORAGE_ACCESS_KEY_ID
let secretAccessKey = process.env.STORAGE_SECRET_ACCESS_KEY

const SECRETS_FILE = '/data/.storage.env'

const BUCKETS = [
  'file',
  'image',
  'video',
  'audio',
  'conversation',
  'namespace',
  'session',
  'space',
  'temp',
  'output',
]

for (const [name, value] of Object.entries({
  GARAGE_ADMIN_URL: base,
  GARAGE_ADMIN_TOKEN: token,
})) {
  if (!value) {
    console.error(`[garage-init] ${name} is not set`)
    process.exit(1)
  }
}

if (Boolean(accessKeyId) !== Boolean(secretAccessKey)) {
  console.error(
    '[garage-init] STORAGE_ACCESS_KEY_ID and STORAGE_SECRET_ACCESS_KEY must be set together'
  )

  process.exit(1)
}

async function api(path, body) {
  const response = await fetch(base + path, {
    ...(body && { method: 'POST', body: JSON.stringify(body) }),
    headers: {
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
    },
  })

  const text = await response.text()

  if (!response.ok) {
    throw new Error(`${path} -> ${response.status}: ${text.slice(0, 200)}`)
  }

  return text ? JSON.parse(text) : null
}

// @note the compose healthcheck gates on the RPC port; give the admin API a
// short grace period of its own
let status

for (let attempt = 0; ; attempt++) {
  try {
    status = await api('/v2/GetClusterStatus')

    break
  } catch (error) {
    if (attempt >= 30) {
      throw error
    }

    await new Promise((resolve) => setTimeout(resolve, 1000))
  }
}

const node = status.nodes[0]

if (!node.role) {
  await api('/v2/UpdateClusterLayout', {
    roles: [{ id: node.id, zone: 'dc1', capacity: 1000000000, tags: [] }],
  })

  const layout = await api('/v2/GetClusterLayout')

  await api('/v2/ApplyClusterLayout', { version: layout.version + 1 })

  console.log('[garage-init] single-node layout applied')
}

if (!accessKeyId) {
  try {
    const saved = readFileSync(SECRETS_FILE, 'utf8')

    accessKeyId = saved.match(/^GENERATED_STORAGE_ACCESS_KEY_ID=(.+)$/m)?.[1]
    secretAccessKey = saved.match(
      /^GENERATED_STORAGE_SECRET_ACCESS_KEY=(.+)$/m
    )?.[1]
  } catch {
    // no persisted key yet - generate one below
  }
}

if (!accessKeyId) {
  const key = await api('/v2/CreateKey', { name: 'platform' })

  accessKeyId = key.accessKeyId
  secretAccessKey = key.secretAccessKey

  writeFileSync(
    SECRETS_FILE,
    `GENERATED_STORAGE_ACCESS_KEY_ID=${accessKeyId}\nGENERATED_STORAGE_SECRET_ACCESS_KEY=${secretAccessKey}\n`,
    { mode: 0o600 }
  )

  // @note the application image runs as uid/gid 1001 and must read the file
  chownSync(SECRETS_FILE, 1001, 1001)

  console.log('[garage-init] access key generated')
}

const keys = await api('/v2/ListKeys')

if (!keys.some((key) => key.id === accessKeyId)) {
  await api('/v2/ImportKey', { accessKeyId, secretAccessKey, name: 'platform' })

  console.log('[garage-init] access key imported')
}

function sha256(data) {
  return createHash('sha256').update(data).digest('hex')
}

function hmac(key, data, encoding) {
  return createHmac('sha256', key).update(data).digest(encoding)
}

// @note minimal SigV4 for one path-style request - enough to avoid pulling
// the AWS SDK into the initializer image for a single call
async function s3(method, bucket, query, body) {
  const url = new URL(`/${bucket}?${query}`, s3Url)

  const amzDate = new Date().toISOString().replace(/[-:]|\.\d{3}/g, '')
  const date = amzDate.slice(0, 8)
  const scope = `${date}/${s3Region}/s3/aws4_request`
  const payloadHash = sha256(body)

  const headers = {
    host: url.host,
    'x-amz-content-sha256': payloadHash,
    'x-amz-date': amzDate,
  }

  const signedHeaders = Object.keys(headers).sort().join(';')

  const canonicalRequest = [
    method,
    url.pathname,
    `${query}=`,
    ...Object.keys(headers)
      .sort()
      .map((name) => `${name}:${headers[name]}`),
    '',
    signedHeaders,
    payloadHash,
  ].join('\n')

  const stringToSign = [
    'AWS4-HMAC-SHA256',
    amzDate,
    scope,
    sha256(canonicalRequest),
  ].join('\n')

  const signingKey = ['s3', 'aws4_request'].reduce(
    (key, part) => hmac(key, part),
    hmac(hmac(`AWS4${secretAccessKey}`, date), s3Region)
  )

  const signature = hmac(signingKey, stringToSign, 'hex')

  const response = await fetch(url, {
    method,
    body,
    headers: {
      ...headers,
      authorization: `AWS4-HMAC-SHA256 Credential=${accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`,
      'content-type': 'application/xml',
    },
  })

  if (!response.ok) {
    throw new Error(
      `${method} /${bucket}?${query} -> ${response.status}: ${(await response.text()).slice(0, 200)}`
    )
  }
}

const corsConfiguration =
  '<CORSConfiguration><CORSRule>' +
  corsOrigins
    .map((origin) => `<AllowedOrigin>${origin}</AllowedOrigin>`)
    .join('') +
  ['GET', 'PUT', 'HEAD'].map((m) => `<AllowedMethod>${m}</AllowedMethod>`).join('') +
  '<AllowedHeader>*</AllowedHeader>' +
  '<ExposeHeader>ETag</ExposeHeader>' +
  '<MaxAgeSeconds>3600</MaxAgeSeconds>' +
  '</CORSRule></CORSConfiguration>'

const buckets = await api('/v2/ListBuckets')

for (const alias of BUCKETS) {
  let bucket = buckets.find((entry) => entry.globalAliases?.includes(alias))

  if (!bucket) {
    bucket = await api('/v2/CreateBucket', { globalAlias: alias })
  }

  await api('/v2/AllowBucketKey', {
    bucketId: bucket.id,
    accessKeyId,
    permissions: { read: true, write: true, owner: true },
  })

  await s3('PUT', alias, 'cors', corsConfiguration)
}

console.log(
  `[garage-init] buckets ready: ${BUCKETS.join(' ')} (cors: ${corsOrigins.join(' ')})`
)
